version: '2'
services:
    j3-app:
        image: j3
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://j3-mysql:3306/j3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    j3-mysql:
        extends:
            file: mysql.yml
            service: j3-mysql
